plugins {
    id 'com.android.application'
}

android {
    namespace 'shop.sntat.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'shop.sntat.mobile'
        minSdk 24
        targetSdk 35
        versionCode 139
        versionName '1.3.9'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // Use Android Studio > Build > Generate Signed App Bundle or APK
            // and your original signing key to publish upgrades.
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig true
    }
}
